// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xznqsklwrodetxxvrcoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bnFza2x3cm9kZXR4eHZyY29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTY5MDQsImV4cCI6MjA3MDMzMjkwNH0.VVG06XkXg6lWCdP_dPSWh9vXat9qi0e2JGBpvplS25I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});